import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='assets/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>FE플랫폼 보일러플레이트</span>
        </h1>

        <p className={styles.description}></p>

        <div className={styles.grid}>
          <a
            href='https://www.notion.so/t3q/FE-82d9dbd0b89747e190e9f74a805ef3f2'
            className={styles.card}
          >
            <h2>Documentation &rarr;</h2>
          </a>

          <a
            href='https://www.notion.so/t3q/d56d0844e04449d39b5d7791829996d2'
            className={styles.card}
          >
            <h2>Setting Process &rarr;</h2>
          </a>

          <Link href='/sample' className={styles.card}>
            <h2>sample page &rarr;</h2>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='assets/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
